--- 
categories: 
- UFBA
- AJUSTAMENTO 
- COLAB 
date: 2026-06-16
description: teste 
image: images.jpg
title: "aula de ajustamento de umma poligonal fechada"
---

<a href="https://colab.research.google.com/github/Alixandrini/ENGJ22/blob/main/Aula%2010/Exerc%C3%ADcos_aula_10.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

#Ajustamento de uma poligonal fechada
## Exercíco Propósto
### Exemplo 01 
Seja uma poligonal fechada com quatro vértices, apresentada na figura abaixo, onde foram observados distancias e ângulos internos ao poligono, em caminhamento no sentido horário. São conhecidas as coordenadas do ponto inicial A e o azimute da direação AB :

| Descrição  | Distância (m) | Desvio padrão ($\ \sigma$\)|
|---------| ---------| ---------| 
|$\ X_{A}$ | 1000.00  | 0.001 |
|$\ Y_{A}$ | 1000.00   | 0.001 |
|$\ Azimute_{AB}$ |45$^{\circ}$ 00' 00"    | 10" |

A tabela seguinte apresnta os valores observados com seus respectivos desvios padrão.

| Observações  | Ângulo | Desvio padrão|  Distância (m) | Desvio padrão (m)|
|---------| ---------| ---------| ---------| ---------| 
|$\ \alpha_{1}$ |112$^{\circ}$ 50' 27"| 10" | 214.970    | 5mm+2ppm |
|$\ \alpha_{2}$ |113$^{\circ}$ 30' 58"| 10" | 267.600    | 5mm+2ppm |
|$\ \alpha_{3}$ |66$^{\circ}$ 40' 25" | 10" | 425.660    | 5mm+2ppm |
|$\ \alpha_{4}$ |66$^{\circ}$ 58' 09" | 10" | 267.790    | 5mm+2ppm|


<img src=https://raw.githubusercontent.com/Alixandrini/ENGJ22/main/Aula%2010/poligonal.png>




#### Resolução
Os parâmetros são constituídos pelas coordenadas dos vértices B,C e D. Como as coordenadas do vértice A apresentam inprecisões, temos que tais coordenadas devem participar dos parâmetros e, no ajustamento, introduzir injunções de posição.

In [1]:
import numpy as np

Lb=np.matrix([[214.970],
              [267.600],
              [425.660],
              [267.790],
              [(112+50/60+27/3600)*np.pi/180],
              [(113+30/60+58/3600)*np.pi/180],
              [(66+40/60+25/3600)*np.pi/180],
              [(66+58/60+9/3600)*np.pi/180]])
#Coordenada aproximadas
x1,y1 = 1000,1000
az12=45*np.pi/180
x2=x1+Lb[0,0]*np.sin(az12)
y2=y1+Lb[0,0]*np.cos(az12)
az23=az12+np.pi-Lb[5,0]
x3=x2+Lb[1,0]*np.sin(az23)
y3=y2+Lb[1,0]*np.cos(az23)
az34=az23+np.pi-Lb[6,0]
x4=x3+Lb[2,0]*np.sin(az34)
y4=y3+Lb[2,0]*np.cos(az34)
X0=np.matrix([[x1],
              [y1],
              [x2],
              [y2],
              [x3],
              [y3],
              [x4],
              [y4]])
X0

matrix([[1000.        ],
        [1000.        ],
        [1152.00674475],
        [1152.00674475],
        [1401.0140542 ],
        [1054.00103145],
        [1101.0252817 ],
        [ 752.01895918]])

In [2]:
#Matriz dos Pesos
P=np.zeros((8,8))
P[0,0]=1/np.sqrt(5**2+2*Lb[1,0]/1000**2)*10**(-6)
P[1,1]=1/np.sqrt(5**2+2*Lb[1,0]/1000**2)*10**(-6)
P[2,2]=1/np.sqrt(5**2+2*Lb[2,0]/1000**2)*10**(-6)
P[3,3]=1/np.sqrt(5**2+2*Lb[3,0]/1000**2)*10**(-6)
P[4,4]=1/(10/3600*np.pi/180)**2
P[5,5]=1/(10/3600*np.pi/180)**2
P[6,6]=1/(10/3600*np.pi/180)**2
P[7,7]=1/(10/3600*np.pi/180)**2
P


array([[1.99997859e-07, 0.00000000e+00, 0.00000000e+00, 0.00000000e+00,
        0.00000000e+00, 0.00000000e+00, 0.00000000e+00, 0.00000000e+00],
       [0.00000000e+00, 1.99997859e-07, 0.00000000e+00, 0.00000000e+00,
        0.00000000e+00, 0.00000000e+00, 0.00000000e+00, 0.00000000e+00],
       [0.00000000e+00, 0.00000000e+00, 1.99996595e-07, 0.00000000e+00,
        0.00000000e+00, 0.00000000e+00, 0.00000000e+00, 0.00000000e+00],
       [0.00000000e+00, 0.00000000e+00, 0.00000000e+00, 1.99997858e-07,
        0.00000000e+00, 0.00000000e+00, 0.00000000e+00, 0.00000000e+00],
       [0.00000000e+00, 0.00000000e+00, 0.00000000e+00, 0.00000000e+00,
        4.25451703e+08, 0.00000000e+00, 0.00000000e+00, 0.00000000e+00],
       [0.00000000e+00, 0.00000000e+00, 0.00000000e+00, 0.00000000e+00,
        0.00000000e+00, 4.25451703e+08, 0.00000000e+00, 0.00000000e+00],
       [0.00000000e+00, 0.00000000e+00, 0.00000000e+00, 0.00000000e+00,
        0.00000000e+00, 0.00000000e+00, 4.25451703e+08, 0.

## Funções no Python
Na programação, funções são blocos de código que realizam determinadas tarefas que normalmente precisam ser executadas diversas vezes dentro de uma aplicação. Quando surge essa necessidade, para que várias instruções não precisem ser repetidas, elas são agrupadas em uma função, à qual é dado um nome e que poderá ser chamada/executada em diferentes partes do programa.
### Criando funções no Python
 sintaxe de uma função é definida por três partes: nome, parâmetros e corpo, o qual agrupa uma sequência de linhas que representa algum comportamento. No código abaixo, temos um exemplo de declaração de função em Python:
```Python
 def hello(meu_nome):
  print('Olá',meu_nome)
```
Essa função, de nome `hello`, tem como objetivo imprimir o nome que lhe é passado por parâmetro (também chamado de argumento). A palavra reservada `def`, na primeira linha, explicita a definição da função naquele ponto. Em seguida, entre parênteses, temos o parâmetro `meu_nome`. Ainda na mesma linha, observe a utilização dos dois pontos (:), que indicam que o código identado nas linhas abaixo faz parte da função que está sendo criada. Aqui, é importante ressaltar que, para respeitar a sintaxe da linguagem, a linha 2 está avançada em relação à linha 1.

Para executar a função, de forma semelhante ao que ocorre em outras linguagens, devemos simplesmente chamar seu nome e passar os parâmetros esperados entre parênteses, conforme o código a seguir.
```Python
>>> hello('Mauro')
Olá Mauro
>>> meu_nome
'Mauro'
```
Caso seja necessário, também é possível definir funções com nenhum ou vários argumentos, como no código abaixo:
```Python
def hello(meu_nome,idade):
   print('Olá',meu_nome,'\nSua idade é:',idade)
   ```
   Agora, ao invocar essa função, também é necessário informar o segundo parâmetro, que representa a idade que será impressa após o nome:
```Python
>>> hello('Mauro',38)
Olá Mauro
Sua idade é: 38
```
Assim como podem receber valores de entrada, as funções também podem produzir valores de saída, provenientes de determinadas operações. Nos exemplos anteriores, apenas imprimimos um valor com a função `print`, sem retornar explicitamente um resultado. Já na Listagem 1, temos uma função que faz o cálculo do salário e retorna o valor a ser pago conforme o número de horas trabalhadas. 
```Python
def calcular_pagamento(qtd_horas, valor_hora):
  horas = float(qtd_horas)
  taxa = float(valor_hora)
  if horas <= 40:
    salario=horas*taxa
  else:
    h_excd = horas - 40
    salario = 40*taxa+(h_excd*(1.5*taxa))
  return salario
  ````
  Na linha 1, a função `calcular_pagamento()` recebe dois parâmetros, `qtd_horas` e `valor_hora`, que representam, respectivamente, a quantidade de horas a serem calculadas e o valor da hora. Nas linhas 2 e 3, esses valores são convertidos para o tipo float, pois eles serão recebidos como string por meio da instrução `input`.

Na quarta linha, verificamos se a quantidade de horas trabalhadas é menor ou igual a 40. Caso seja verdadeiro, na linha 5 calculamos o valor do salário apenas multiplicando a quantidade de horas pelo valor de cada hora trabalhada. Se a quantidade for maior que 40 (linha 6), adicionamos ao salário um valor adicional pelas horas extras. Por fim, na linha 9 retornamos o resultado do cálculo (contido na variável `salario`) com a instrução `return`.

No código abaixo, vemos como utilizar essa função, obtendo seu retorno e o imprimindo na tela posteriormente:
```
str_horas= input('Digite as horas: ')
str_taxa=input('Digite a taxa: ')
total_salario = calcular_pagamento(str_horas,str_taxa)
print('O valor de seus rendimentos é R$',total_salario)
```
Primeiramente, solicitamos do usuário as informações necessárias, que serão armazenadas como string e repassadas para a função (linhas 1 e 2). Em seguida, na linha 3, obtemos o resultado da função e o atribuímos à variável `total_salario`, que é impressa na linha 4.

A Listagem 2 mostra a execução desse código em duas situações.
```
Digite as horas: 40
Digite a taxa: 20
O valor de seus rendimentos é:  800.0
>>>
Digite as horas: 50
Digite a taxa: 20
1100.0
```
Nesse caso, definimos explicitamente que a função deve retornar um determinado resultado por meio da instrução return. Caso isso não seja feito, o valor padrão retornado será None, equivalente ao null, void ou nil encontrado em outras linguagens.
Parâmetros nomeados

As funções em Python tem suporte a parâmetros nomeados. O exemplo a seguir mostra um caso onde podemos usar nomes nos parâmetros da função.
```
def calculo_imc(peso, altura):
    print(peso / altura ** 2)

calculo_imc(75, 1.68)
```
Observe que quando chamamos a função calculo_imc, não há uma identificação do que cada valor representa dentro daquela função. Nesse mesmo exemplo usando essa funcionalidade, conseguimos ver melhor como podemos dar nome aos parâmetros.
```
def calculo_imc(peso, altura):
    print(peso / altura ** 2)

calculo_imc(peso = 75, altura = 1.68)
```
Mesmo que venhamos a trocar a ordem dos argumentos na chamada da função, ela será executada corretamente da mesma forma, pois os parâmetros estão sendo identificados por um nome e não pela sua posição.

Fonte:https://www.devmedia.com.br/funcoes-em-python/37340

In [ ]:
import numpy as np
#função de calculo de azimutes
def azimute(x1,y1,x2,y2):
  if (y2>y1 and x2>=x1):                  #Primeiro Quadrante
    azim=np.arctan((x2-x1)/(y2-y1))
  if (y2>y1 and x1>x2):                   #Quarto Quadrante
    azim=np.arctan((x1-x2)/(y2-y1))
  if (y2==y1 and x2>=x1):                 #90 graus
    azim=np.pi/2
  if (y2==y1 and x2>x1):                  #270 graus
    azim=3*np.pi/2
  if (y2<y1 and x2>=x1):
    azim=np.pi-np.arctan((x2-x1)/(y1-y2))   #Segundo Quadrante
    else:
      azim=np.pi+np.arctan((x1-x2)/(y1-y2)) #Terceiro Quadrante
  return azim
#função de calculo de angulo sentido USR
def CalcAngulo(xu,yu,xr,yr,xs,ys):
  if (ys>yu and xs>=xu):                      #Primeiro Quadrante
    alfaUS=np.arctan((xs-xu)/(ys-yu))
  if (ys>yu and xs<xu):                       #Quarto Quadrante
    alfaUS=2*np.pi-np.arctan((xu-xs)/(ys-yu))
  if (ys==yu and xs>=xu):                     #90 graus
    alfaUS=np.pi/2
  if (ys==yu and xs>xu):                      #270 graus
    alfaUS=3*np.pi/2
  if (ys<yu and xs>=xu):
    alfaUS=np.pi-np.arctan((xs-xu)/(yu-ys))   #Segundo Quadrante
    else:
      alfaUS=np.pi+np.arctan((xu-xs)/(yu-ys)) #Terceiro Quadrante
  if (yr>ys and xr>=xs):                      #Primeiro Quadrante
    alfaSR=np.arctan((xr-xs)/(yr-ys))
  if (ys>yu and xs<xu):                       #Quarto Quadrante
    alfaSR=2*np.pi-np.arctan((xs-xr)/(yr-ys))
  if (yr==ys and xr>=xs):                     #90 graus
    alfaSR=np.pi/2
  if (yr==ys and xr>xs):                      #270 graus
    alfaSR=3*np.pi/2
  if (yr<ys and xr>=xs):
    alfaSR=np.pi-np.arctan((xr-xs)/(ys-yr))   #Segundo Quadrante
    else:
      alfaSR=np.pi+np.arctan((xs-xr)/(ys-yr)) #Terceiro Quadrante
  return alfaUS, alfaSR
#função da derivada da função ângulo de duas direções
def CalcDerivAngulo(xa,ya,xb,yb,xc,yc):
  dAB2=(xa-xb)**2+(ya-yb)**2
  if (yb==ya):
    deriv=np.array([0,0,0,0,0,0])
    else:
      deriv=np.array([(ya-yb),(xb-xa),(yb-ya),(xa-xb),0,0])/dAB2
  dBC2=(xb-xc)**2+(yb-yc)**2
  if(yc~=yb):
    deriv=deriv-np.array([0,0,(yb-yc),(xc-xb),(yc-yb),(xb-xc)])/dBC2
    return deriv
#Calculo da distância entre dois pontos
def DstCoord(xa,ya,xb,yb):
  dista=np.sqrt((xb-xa)**2+(yb-ya)**2)
  return dista
#Calculo Matriz de Rotação
def ome_phi_kap(ome,phi,kap):
  M=np.zeros(3,3)
  M[0,0]=np.cos(phi)*np.cos(kap)
  M[0,1]=np.cos(ome)*np.sin(kap)+np.sin(ome)*np.sin(phi)*np.cos(kap)
  M[0,2]=np.sin(ome)*np.sin(kap)-np.cos(ome)*np.sin(phi)*np.cos(kap)
  M[1,0]=-np.cos(phi)*np.sin(kap)
  M[1,1]=np.cos(ome)*np.cos(kap)-np.sin(ome)*np.sin(phi)*np.sin(kap)
  M[1,2]=np.sin(ome)*np.cos(kap)+np.cos(ome)*np.sin(phi)*np.sin(kap)
  M[2,0]=np.sin(phi)
  M[2,1]=-np.sin(ome)*np.cos(phi)
  M[2,2]=np.cos(ome)*np.cos(phi)
  return M
#calculo das Elipses dos Erros
def elipse(varX,varY,covarXY)
M=np.sqrt(4*covarXY**2+(varX-varY)**2)
varMax=(varX+varY+M)/2
VarMin=(varX+varY-M)/2
a=np.sqrt(varMax)
b=np.sqrt(varMin)
#casos especiais
if covarXY==0:
  if varX>=varY:
    t=0
    else:
      t=90
  else:
    if varX==varY:
      if covarXY>0:
        t=45
        else:
          t=135
      else:
        t2=np.arctan(abs(2*covarXY/(varX-varY)))*180/np.pi
#Análise do quadrante
        if covarXY>0:
          if varX>varY:
            #primeiro Quadrante
            t=t2/2
            else:
              #segundo Quadrante
              t=(180-t2)/2
        else:
          if varX<varY:
            #Terceiro Quadrante
            t=(180+t2)/2
          else:
            t=(360-t2)/2

return [a,b,t]









In [ ]:
import numpy as np
A=np.array([2,3])
A/5

array([0.4, 0.6])